name: "CI Checks and Tests"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Dependabot
        uses: SkynetLabs/.github/actions/npm-basic-checks@dependabot-and-npm-checks
        with:
          node-version: ${{ matrix.node-version }}
